/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126497-g5b614efc7e-20260911"
#endif /* AVUTIL_FFVERSION_H */
